// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB82RW8CAFyv1NgHaR2vFqLuYYhC2dHKy0',
    appId: '1:670775742773:web:b32b621cdbf906b4db3c7c',
    messagingSenderId: '670775742773',
    projectId: 'my-cloud-firestore-flutt-890e8',
    authDomain: 'my-cloud-firestore-flutt-890e8.firebaseapp.com',
    storageBucket: 'my-cloud-firestore-flutt-890e8.firebasestorage.app',
  );


  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9aJHqsWY6fm4Eb2AY6UNXDDlxNK08EPk',
    appId: '1:670775742773:android:13dba225b7ff36bcdb3c7c',
    messagingSenderId: '670775742773',
    projectId: 'my-cloud-firestore-flutt-890e8',
    storageBucket: 'my-cloud-firestore-flutt-890e8.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB82RW8CAFyv1NgHaR2vFqLuYYhC2dHKy0',
    appId: '1:670775742773:web:11b88f33ba718677db3c7c',
    messagingSenderId: '670775742773',
    projectId: 'my-cloud-firestore-flutt-890e8',
    authDomain: 'my-cloud-firestore-flutt-890e8.firebaseapp.com',
    storageBucket: 'my-cloud-firestore-flutt-890e8.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBneuGYIuWyWCIyuhaOv4Z4SnCD6xRAvuw',
    appId: '1:670775742773:ios:230a08364e2b1127db3c7c',
    messagingSenderId: '670775742773',
    projectId: 'my-cloud-firestore-flutt-890e8',
    storageBucket: 'my-cloud-firestore-flutt-890e8.firebasestorage.app',
    iosBundleId: 'com.example.myFirebaseCloudFirestoreApp',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBneuGYIuWyWCIyuhaOv4Z4SnCD6xRAvuw',
    appId: '1:670775742773:ios:230a08364e2b1127db3c7c',
    messagingSenderId: '670775742773',
    projectId: 'my-cloud-firestore-flutt-890e8',
    storageBucket: 'my-cloud-firestore-flutt-890e8.firebasestorage.app',
    iosBundleId: 'com.example.myFirebaseCloudFirestoreApp',
  );

}